### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VegeBun-csj** [DoraFactory/multisig-app#4]
- [x] login with exist multisig with the owner account @VegeBun-csj 
- [ ] change the walletCreation step2 and step3 to the latest design @99Kies 
- [ ] fix getting the `threshold` value `0` when user input manually  @VegeBun-csj 
- [x] add the function of removing owner input in walletCreation. @99Kies 
- [x] complete the multisig transaction module @VegeBun-csj  @99Kies 
- [ ] add Polkadot and Kusama's coin card modal. @99Kies 
- [ ] add some tips ui  @VegeBun-csj  @99Kies 
- [ ] must >= two accounts can we create a multisig account

maybe some bugs:
- [ ] if owners' name is long, the copy icon will flow @99Kies 
- [ ] **fix the api**(when fresh the page, the api from the context will miss)  @VegeBun-csj 

main tasks:
- [ ] add xtoken currency transfer  @VegeBun-csj 
- [ ] switch different network in home page dropdown. @VegeBun-csj
- [ ] tips ui 交互。@VegeBun-csj
- [ ] step3的样式调整。@99Kies 
- [ ] add multisig account dropdown  @99Kies 
- [ ] CSS样式引入的冲突解决（fix all the copy icon）@99Kies
- [ ] 后端联调 ---- 接口调用 @VegeBun-csj  @99Kies

Last, clean  and compress the source code !
